---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- name: boshrelease-ci
- name: candidate-release
- name: version

outputs:
- name: manifest

params:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT:

  delete_deployment_first: false
  base_manifest:
  op_patch_files: "" # comma separated list of relative files

  cf_api_url:
  cf_skip_ssl_validation:
  cf_admin_username: admin
  cf_admin_password:

run:
  path: boshrelease-ci/ci/tasks/bosh2-deploy.sh
