---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- name: boshrelease-ci
- name: candidate-release
- name: version

outputs:
- name: manifest

params:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT:

  errand:

run:
  path: boshrelease-ci/ci/tasks/bosh2-errand.sh
