name: docker-swarm
# TODO add TLS certs
# TODO docker-swarm-sanity-test job

instance_groups:
- name: docker
  instances: 3
  azs: [z1, z2, z3]
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  update: {serial: true}
  jobs:
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls: true
      tls_verify: true
      tls_cacert: "((docker_tls.ca))"
      tls_cert: "((docker_tls.certificate))"
      tls_key: "((docker_tls.private_key))"

- name: swarm
  instances: 1
  azs: [z1, z2, z3]
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: swarm_manager
    release: docker

variables:
- name: docker_ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker_tls
  type: certificate
  options:
    ca: docker_ca
    common_name: docker
    extended_key_usage:
    - client_auth

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: docker
  version: 30.0.0-rc.3
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v30.0.0-rc.3/docker-30.0.0-rc.3.tgz
  sha1: 2cbd5d0a9cfdfacede55d0231a75893f824f32dd
