---
docker/docker-0.10.0:
  object_id: 2f66df0c-312d-4745-873b-ce6a784ea682
  sha: !binary |-
    MzgyZjIwNWJjZmM1ODYzNzlhZjk1ZGM5N2Q0OWIzODVjY2E1ODUxZA==
  size: 16970072
docker/aufs-tools_20120411-3_amd64.deb:
  object_id: 0866debb-d731-4c1c-b442-3294247506e8
  sha: !binary |-
    MmRmYzFmZTM4NmNkM2YwNWFjN2UwYjRlYmNmM2ViYzhhN2YzYjA0ZA==
  size: 91762
docker/docker-0.11.0:
  object_id: b71c68ee-9350-4032-85fa-09b4c6e94ad7
  sha: !binary |-
    YTAwNDMwMzhlODZjZjMxNjBhODIyM2EwYWQzMGZiYTg5NmU0MDg2Yw==
  size: 17239732
docker/docker-1.0.0:
  object_id: efd9ee03-5c99-4e8b-96e4-ba0290248cd9
  sha: !binary |-
    YTYyYmM5NzUxOGY0NTU0NDE4ZTdhNmU4M2IwMmZkZmZlOWVkN2VlNg==
  size: 17578488
logspout/logspout-9a0a67fe4b:
  object_id: 806b0eaa-9313-439c-9953-2886109495c7
  sha: !binary |-
    NGM3Nzk0YWQ4MDE2NTlmYzM2Yjc0YjJmNWYwMTg1NzJjZjdjNjY0MA==
  size: 9567640
ruby/ruby-2.0.0-p481.tar.gz:
  object_id: 4f7f71bb-8de6-46bb-89ee-25dd7326ea9e
  sha: !binary |-
    ZGRlZDdiNzM0OWQ1OWZlYjgzZDRmNzc0YjJkZGVjMjNlZWFiNzk3OA==
  size: 13586757
ruby/bundler-1.6.3.gem:
  object_id: fab3cfc3-1750-4fac-8543-a01c16ebaeb7
  sha: !binary |-
    YzhhMDAwZjc1YjZhNmY2MGQ5ZmI3MjdmODA3NmVjOTE3MWUxNGMyMA==
  size: 293376
ruby/rubygems-2.3.0.tgz:
  object_id: 5b5998b4-c06b-458a-ba4f-cac005365cc6
  sha: !binary |-
    NjkwMmZmZjc3NDlmYTI2NGI4ZjkwMjBmMzNkYWY5MjE3MDM3NWY3NQ==
  size: 431240
ruby/yaml-0.1.6.tar.gz:
  object_id: f83bdc13-d038-4cda-abe3-b477d3fabbba
  sha: !binary |-
    ZjNkNDA0ZTExYmVjM2M0ZWZjZGRmZDE0YzQyZDQ2ZjFhYWJlMGI1ZA==
  size: 503012
