<%
director_uuid = 'CHANGE-ME'
deployment_name = 'docker-swarm'
elastic_ip = 'CHANGE-ME'
num_docker_nodes = 3
%>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: docker
   version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.xlarge

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
        - bosh
        - <%= deployment_name %

  - name: elastic
    type: vip
    cloud_properties: {}

resource_pools:
  - name: default
    network: default
    size: <%= num_docker_nodes + 1 %>
    stemcell:
      name: bosh-aws-xen-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.xlarge

jobs:
  - name: docker
    templates:
      - name: docker
    instances: <%= num_docker_nodes %>
    resource_pool: default
    persistent_disk: 65536
    networks:
      - name: default
        default: [dns, gateway]

  - name: swarm
    templates:
      - name: swarm_manager
    instances: 1
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]
      - name: elastic
        static_ips:
          - <%= elastic_ip %>

properties:
  docker:
    tcp_address: 0.0.0.0

  swarm_manager:
    docker_nodes:
      <% num_docker_nodes.times do |i| %>
      <%= "- #{i}.docker.default.#{deployment_name}.microbosh\n" %>
      <% end %>
