<% director_uuid = 'CHANGE-ME' %>
<% deployment_name = 'docker' %>
<% floating_ip = 'CHANGE-ME' %>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: docker
   version: latest

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.xlarge

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
        - bosh
        - <%= deployment_name %>

  - name: floating
    type: vip
    cloud_properties: {}

resource_pools:
  - name: default
    network: default
    size: 1
    stemcell:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.xlarge

jobs:
  - name: docker
    templates:
      - name: docker
      - name: containers
    instances: 1
    resource_pool: default
    persistent_disk: 65536
    networks:
      - name: default
        default: [dns, gateway]
      - name: floating
        static_ips:
          - <%= floating_ip %>
    properties:
      containers:
        - name: redis
          image: "redis"
          command: "--dir /var/lib/redis/ --appendonly yes"
          bind_ports:
            - "6379:6379"
          bind_volumes:
            - "/var/lib/redis"
          entrypoint: "redis-server"
          memory: "256m"
          cpu_shares: 1
          env_vars:
            - "EXAMPLE_VAR=1"

        - name: mysql
          image: "google/mysql"
          bind_ports:
            - "3306:3306"
          bind_volumes:
            - "/mysql"

        - name: elasticsearch
          image: "bosh/elasticsearch"
          links:
            - mysql:db
          depends_on:
            - mysql
          bind_ports:
            - "9200:9200"
            - "9300:9300"
          bind_volumes:
            - "/data"
          dockerfile: |
            FROM dockerfile/java

            RUN \
              cd /tmp && \
              wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.1.tar.gz && \
              tar xvzf elasticsearch-1.1.1.tar.gz && \
              rm -f elasticsearch-1.1.1.tar.gz && \
              mv /tmp/elasticsearch-1.1.1 /elasticsearch

            WORKDIR /data

            CMD ["/elasticsearch/bin/elasticsearch"]

            EXPOSE 9200
            EXPOSE 9300

properties: {}
