<%
director_uuid = 'CHANGE-ME'
deployment_name = 'docker-swarm'
%>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: docker
   version: latest

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  canaries: 0
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    type: manual
    subnets:
      - cloud_properties: {}
        range: 10.244.0.0/24
        reserved:
          - 10.244.0.1
        static:
          - 10.244.0.2
          - 10.244.0.3
          - 10.244.0.4

resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties: {}

jobs:
  - name: docker
    templates:
      - name: docker
    instances: 2
    resource_pool: default
    persistent_disk: 65536
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.244.0.2
          - 10.244.0.3
    update:
      serial: true

  - name: swarm
    templates:
      - name: swarm_manager
    instances: 1
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.244.0.4

properties:
  docker:
    tcp_address: 0.0.0.0

  swarm:
    discovery: "nodes://10.244.0.2:4243,10.244.0.3:4243"
