<%
director_uuid = 'CHANGE-ME'
deployment_name = 'docker-swarm'
static_ip = 'CHANGE-ME'
num_docker_nodes = 3
%>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: docker
   version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    machine_type: n1-standard-8
    preemptible: true

update:
  canaries: 0
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    type: dynamic
    cloud_properties:
      ephemeral_external_ip: true
      tags:
        - bosh
        - <%= deployment_name %>

  - name: static
    type: vip
    cloud_properties: {}

resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      machine_type: n1-highmem-8

jobs:
  - name: docker
    templates:
      - name: docker
    instances: <%= num_docker_nodes %>
    resource_pool: default
    persistent_disk: 65536
    networks:
      - name: default
        default: [dns, gateway]
    update:
      serial: true

  - name: swarm
    templates:
      - name: swarm_manager
    instances: 1
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]
      - name: static
        static_ips:
          - <%= static_ip %>

properties:
  docker:
    tcp_address: 0.0.0.0

  swarm:
    discovery: "nodes://<%= num_docker_nodes.times.map { |i| "#{i}.docker.default.#{deployment_name}.microbosh:4243" }.join(',') %>"
